project:
  type: book
  output-dir: _book
    
book:
  title: "STRAT 490R - Creating Digital Products with AI"
  favicon: images/prototyping-favicon.png
  author: "Scott Murff"
  date: "1/9/2026"
  chapters:
    - part: Course Information
      chapters:
        - index.qmd
        - 00-schedule.qmd
        - 00-assessments.qmd
    - part: Topics
      chapters:
        - 01-pm-ai-era.qmd
        - 02-problems-worth-solving.qmd
        - 03-problem-discovery.qmd
        - 04-validating-opportunities.qmd
        - 05-building-your-mvp.qmd
        - 06-testing-with-users.qmd
        - 07-platform-strategy.qmd
        - 08-measuring-what-matters.qmd
        - 09-go-to-market.qmd
        - 10-business-models.qmd
        - 11-sustainable-code.qmd
        - 12-final-presentations.qmd
    - part: Resources
      chapters:
    # Resources and Appendices
      - 95-eng-checklist.qmd
      - 96-code-base-review.qmd
      - 97-resources.qmd
      - 98-tools.qmd
      - 99-prompts.qmd

bibliography: references.bib
csl: informs.csl

format:
  html:
    include-in-header: _header.html
    include-after-body: _footer.html
    theme: cosmo
    #link-external-icon: true
    link-external-newwindow: true
    css: styles.css
    toc: true
    number-sections: false
execute:
  eval: false
    
toc-title: On this page
